services:
  app:
    build: ./
    image: 'cloudstorage:1.0'
    container_name: 'cloud-storage'
    ports:
      - '8080:8080'
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgress
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  database:
          image: postgres
          container_name: cloudstoragedb
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgress
            POSTGRES_DB: postgres
          ports:
            - "5432:5432"